### ISSUE TITLE
Win version 1.2alpha-1 gets stuck while opening the zip

### ISSUE THREAD

**Issue by Szepi70** [thayakawa-gh/SlackLogViewer#16]
If I feed the app with zip created with slackdump (I tried different setup for export eg standard,mattermost export with files), the app always and immediately hangs up, becomes suspended in task manager, no response on GUI at all, even if I open a very small private conversation (3mb zip, <10 post , 2 attached files). Tried on company laptop (w10) and on private desktop machine (win10 no rules, full admin)  as well , same outcome. V1.2.Alpha-0 behaves the same way for me and V1.1.0 as well :) Please advise, thx

**Comment by thayakawa-gh** [comment]
Hi, @Szepi70.
I'm now trying to add funcsions to detect unexpected json values.
Can you try [this test version](https://github.com/thayakawa-gh/SlackLogViewer/actions/runs/5776225008)? If there are broken messages in your export files, an error message may be appeared. It can be downloaded from Artifacts->windows-qt6.

**Comment by Szepi70** [comment]
Hi @thayakawa-gh. 
Takes ~1 min to process the zip (~350 jsons) and eats up 1,5 gb during this process, while the machine slooooows down, but after that the mem consumption falls back to 700 mb and at least on text level I see the conversation , so this part works , many thx !
However the attached photos don't appear properly, just a placeholder can be seen , though the files referred in the json can be found under the "attachment" folder. Same with the own emojis, like :confluence: :slack: appears instead of the images

**Comment by thayakawa-gh** [comment]
I don't know why your PC uses so much memory. For example, when I open a zip file (~12 MB, ~8800 jsons) with SlackLogViewer 1.2.Alpha-1, it uses only ~100 MB and takes ~1 sec to load. Unless your jsons are extremely large, there may be some bugs.

SlackLogViewer can't load the attachments downloaded by slackdump because it is a unique feature of slackdump. When you use the `-download` option in slackdump, it rewrites URLs of the attachments into local paths to them. So SlackLogViewer can't get the URLs from jsons.
Using `-export-type mattermost -export-token ...` options is the only way to view them in SlackLogViewer as far as I know. However, these options disable downloading of the attachments by slackdump.
In addition, at this time, SlackLogViewer can't display emojis not contained in utf-8.
